import { redirect } from "next/navigation";
import { createServerClient } from "@/lib/supabase/server";
import { ChatInterface } from "@/components/chat/ChatInterface";

export const metadata = { title: "AI Chat" };

export default async function ChatPage() {
  const supabase = createServerClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) redirect("/login");

  return (
    <div className="h-[calc(100vh-8rem)] flex flex-col">
      <div className="mb-4">
        <h1 className="text-2xl font-bold">AI Chat</h1>
        <p className="text-muted-foreground text-sm">
          Chat with your AI assistant. Responses are generated by GPT-4o mini via LangChain.
        </p>
      </div>
      <ChatInterface token={session.access_token} />
    </div>
  );
}
